trigger:
  batch: true
  branches:
    include:
      - master
      - refs/tags/v*

pr:
  - master

variables:
  PYTHONUNBUFFERED: 1
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
  CONDA_PKGS_DIRS: $(Pipeline.Workspace)/.conda

jobs:
  - template: ci/job.test.yml
