trigger:
  batch: true
  branches:
    include:
      - master
      - refs/tags/v*

pr:
  branches:
    include:
      - '*'

variables:
  PYTHONUNBUFFERED: 1
  ATEST_RETRIES: 3
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

  PY_JLSP_VERSION: 0.9.2
  JS_JLLSP_VERSION: 2.0.0
  JS_JLG2D_VERSION: 1.0.0

  FIRST_PARTY_LABEXTENSIONS: >-
    packages/jupyterlab-lsp/krassowski-jupyterlab-lsp-$(JS_JLLSP_VERSION).tgz

  LINKED_EXTENSIONS: >-
    packages/lsp-ws-connection
    packages/jupyterlab-go-to-definition
    packages/completion-theme
    packages/theme-vscode
    packages/theme-material

jobs:
  - template: ci/job.lint.yml
  - template: ci/job.test.yml
