#!/usr/bin/env bash
set -eux
python -m pip install -e . --ignore-installed --no-deps -vv
jupyter serverextension enable --sys-prefix --py jupyter_lsp
pushd vendor/jupyterlab-go-to-definition
  jlpm
  jlpm build
  jupyter labextension install $(npm pack) --no-build
popd
jlpm bootstrap
jupyter labextension install \
  . \
  && jupyter labextension list
