name: jupyterlab-lsp

channels:
  - conda-forge
  - defaults

dependencies:
  # runtime dependencies
  - python >=3.6,<3.9.0a0
  - jupyterlab >=2.2.0,<3.0.0a0
  - notebook >=4.3.1
  # build dependencies
  - nodejs >=10.12,<15
  # for python language server (and development)
  - black
  - flake8 >=3.5
  # isort 5.0 has breaking API changes which affect (among others) pylint and nblint;
  # the pin should be removed once https://github.com/PyCQA/pylint/pull/3725 is merged
  # see https://github.com/krassowski/jupyterlab-lsp/pull/291
  - isort <5
  - mypy
  - pip
  - pylint
  - python-language-server
  - ruamel_yaml
  - pip: # not-yet-appearing-in-conda-forge
      - pyls-black
      - pyls-isort
      - pyls-mypy
  # for R language server and kernel
  - r
  - r-irkernel
  - r-languageserver
  - rpy2
  # for tex
  - tectonic
  - texlab
  - chktex
