name: CI

on:
  push:
    branches:
      - main
      - 3.x
      - 4.x
  pull_request:
    branches:
      - main
      - 3.x
      - 4.x
  workflow_dispatch:

# TODO: might need to tweak `group`
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

env:
  JULIA_NUM_THREADS: 2
  MAMBA_NO_BANNER: 1
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  PYTHONUNBUFFERED: 1

  ATEST_PROCESSES: 2
  ATEST_RETRIES: 3
  JLPM_CMD: jlpm install
  # pixi
  PIXI_RUN: pixi run # -v # uncomment to see inputs/outputs
  PIXI_VERSION: 0.41.4
  PIXI_COLOR: always

  # Increase this value to reset all caches
  CACHE_EPOCH: 5
  JULIA_LANGSERVER: 4.1.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: v${{ env.PIXI_VERSION }}
          cache: true
          environments: build
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            !node_modules/.cache/
            node_modules/
          key: |
            ${{ env.CACHE_EPOCH }}-node-build-${{ hashFiles('pixi.lock', 'yarn.lock') }}
      - run: ${{ env.PIXI_RUN }} setup-js && touch node_modules/.ci-skip-yarn
      - run: ${{ env.PIXI_RUN }} build
      - run: ${{ env.PIXI_RUN }} dist
      - uses: actions/upload-artifact@v4
        with:
          name: jplsp-${{ github.run_number }}-dist
          path: |
            .pixi/task-cache-v0/
            dist/

  lint:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: v${{ env.PIXI_VERSION }}
          cache: true
          environments: build lint
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            !node_modules/.cache/
            node_modules/
          key: |
            ${{ env.CACHE_EPOCH }}-node-build-${{ hashFiles('pixi.lock', 'yarn.lock') }}
      - uses: actions/download-artifact@v4
        with:
          name: jplsp-${{ github.run_number }}-dist
      - run: ${{ env.PIXI_RUN }} fix
      - run: ${{ env.PIXI_RUN }} lint
      - if: always()
        run: pixi run ci-diff >> "${GITHUB_STEP_SUMMARY}"
