name: lint
on: [push, pull_request]

defaults:
  run:
    shell: bash -l {0}

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python:
          - '3.8'
        platform:
          - linux-64
        lab:
          - '2.2'
        include:
          # representative platforms
          - platform: linux-64
            os: ubuntu-16.04
          # Node 14 end-of-life: April 2023
          - python: '3.8'
            nodejs: '14'

    steps:
      - uses: actions/checkout@v2

      - name: Set up conda env
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: jupyterlab-lsp
          auto-activate-base: true
          auto-update-conda: false
          environment-file: requirements/minimal.yml
          python-version: ${{ matrix.python }}

      - name: Overwrite conda env from lockfile
        run: |
          conda create --yes --name jupyterlab-lsp --file .github/conda.locks/conda.lint.${{ matrix.platform }}-${{ matrix.python }}-${{ matrix.lab }}.lock

      - name: check integrity of package versions
        run: python scripts/integrity.py

      - name: install npm dependencies
        run: jlpm

      - name: lint backend
        run: python scripts/lint.py

      - name: build schema so linting can complete
        run: jlpm build:schema

      - name: lint frontend
        run: jlpm lint:check
