# TODO: remove this line which appeases integrity.py
#
#   jupyterlab >=4.1.0,<5.0.0a0
#
name: CI

on:
  push:
    branches:
      - main
      - 3.x
      - 4.x
  pull_request:
    branches:
      - main
      - 3.x
      - 4.x
  workflow_dispatch:

# TODO: might need to tweak `group`
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

env:
  # pixi
  PIXI_COLOR: always
  # python
  PYTHONUNBUFFERED: 1
  # julia
  JULIA_NUM_THREADS: 2
  # this repo
  CACHE_EPOCH: 6 # increase this value to reset all caches
  PIXI_VERSION: 0.41.4 # keep in sync with `pixi.toml#/$schema`
  PIXI_RUN: |- # add `-v` to see more inputs/outputs
    pixi run --no-install --locked

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache pixi env
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: v${{ env.PIXI_VERSION }}
          cache: true
          environments: build
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            !node_modules/.cache/
            **/node_modules/
          key: |
            ${{ env.CACHE_EPOCH }}-node-build-${{ hashFiles('pixi.lock', 'yarn.lock') }}
      - name: Install nodejs dependencies
        run: ${{ env.PIXI_RUN }} setup-js && touch node_modules/.ci-skip-yarn
      - name: Build all intermediates
        run: ${{ env.PIXI_RUN }} build
      - name: Build all distributions
        run: ${{ env.PIXI_RUN }} dist
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: jplsp-${{ github.run_number }}-dist
          path: |
            .pixi/task-cache-v0/
            dist/

  lint:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache pixi env
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: v${{ env.PIXI_VERSION }}
          cache: true
          environments: lint
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            !node_modules/.cache/
            **/node_modules/
          key: |
            ${{ env.CACHE_EPOCH }}-node-build-${{ hashFiles('pixi.lock', 'yarn.lock') }}
      - name: Apply source formatting
        run: ${{ env.PIXI_RUN }} fix
      - name: Run source checks
        run: ${{ env.PIXI_RUN }} lint
      - name: Report changed files
        if: always()
        run: ${{ env.PIXI_RUN }} ci-summary-diff >> "${GITHUB_STEP_SUMMARY}"

  docs:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache pixi env
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: v${{ env.PIXI_VERSION }}
          cache: true
          environments: docs
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            !node_modules/.cache/
            **/node_modules/
          key: |
            ${{ env.CACHE_EPOCH }}-node-build-${{ hashFiles('pixi.lock', 'yarn.lock') }}
      - run: ${{ env.PIXI_RUN }} docs
      - uses: actions/upload-artifact@v4
        with:
          name: jplsp-${{ github.run_number }}-docs
          path: |
            build/docs

  itest:
    needs: [build]
    runs-on: ${{ matrix.os }}-${{ matrix.vm }}
    strategy:
      fail-fast: false
      matrix:
        epoch: [min, now]
        os: [macos, ubuntu, windows]
        vm: [latest]
        include:
          - { epoch: min, os: macos, vm: 13 }
        exclude:
          - { epoch: min, os: macos, vm: latest }
    steps:
      - uses: actions/checkout@v4
      - name: Cache pixi env
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: v${{ env.PIXI_VERSION }}
          cache: true
          environments: itest-${{ matrix.epoch }}
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            !node_modules/.cache/
            **/node_modules/
          key: |
            ${{ env.CACHE_EPOCH }}-node-build-${{ hashFiles('pixi.lock', 'yarn.lock') }}
      - name: Cache julia
        uses: actions/cache@v4
        with:
          path: |
            .pixi/envs/itest-${{ matrix.epoch }}/share/julia
          key: |
            ${{ env.CACHE_EPOCH }}-julia-itest-${{ matrix.epoch }}-${{ matrix.os }}-${{ hashFiles('pixi.lock') }}
      - name: Download PyPI distributions
        uses: actions/download-artifact@v4
        with:
          name: jplsp-${{ github.run_number }}-dist
      - name: |-
          Install PyPI distributions for integration testing (epoch: ${{ matrix.epoch }})
        run: ${{ env.PIXI_RUN }} --skip-deps itest-${{ matrix.epoch }}-uv
      - name: |
          Run integration tests (epoch: ${{ matrix.epoch }})
        run: ${{ env.PIXI_RUN }} --skip-deps itest-${{ matrix.epoch }}
      - if: always()
        name: Publish browser test output
        uses: actions/upload-artifact@v4
        with:
          name: |-
            jplsp-${{ github.run_number }}-itest-${{ matrix.epoch }}-${{ matrix.os }}-${{ matrix.vm }}
          path: ./build/reports

  atest:
    needs: [build]
    runs-on: ${{ matrix.os }}-${{ matrix.vm }}
    strategy:
      fail-fast: false
      matrix:
        epoch: [min, now]
        os: [macos, ubuntu, windows]
        vm: [latest]
        include:
          - { epoch: min, os: macos, vm: 13 }
          - { epoch: pre, os: ubuntu, vm: latest }
        exclude:
          - { epoch: min, os: macos, vm: latest }
    steps:
      - uses: actions/checkout@v4
      - name: Cache pixi env
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: v${{ env.PIXI_VERSION }}
          cache: true
          environments: atest-${{ matrix.epoch }}
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            !node_modules/.cache/
            **/node_modules/
          key: |
            ${{ env.CACHE_EPOCH }}-node-build-${{ hashFiles('pixi.lock', 'yarn.lock') }}
      - name: Cache julia
        uses: actions/cache@v4
        with:
          path: |
            .pixi/envs/atest-${{ matrix.epoch }}/share/julia
          key: |
            ${{ env.CACHE_EPOCH }}-julia-atest-${{ matrix.epoch }}-${{ matrix.os }}-${{ hashFiles('pixi.lock') }}
      - name: Download PyPI distributions
        uses: actions/download-artifact@v4
        with:
          name: jplsp-${{ github.run_number }}-dist
      - name: |-
          Install PyPI distributions for acceptance testing (epoch: ${{ matrix.epoch }})
        run: ${{ env.PIXI_RUN }} --skip-deps atest-${{ matrix.epoch }}-uv
      - name: |-
          Run all acceptance tests (epoch: ${{ matrix.epoch }})
        run: ${{ env.PIXI_RUN }} --skip-deps atest-${{ matrix.epoch }}
      - if: always()
        name: Retry any failed acceptance tests
        timeout-minutes: 30
        env:
          ATEST_ATTEMPT: 1
          ATEST_RETRIES: 4
        run: ${{ env.PIXI_RUN }} --skip-deps atest-${{ matrix.epoch }}
      - if: always()
        name: Summarize acceptance test results
        run: ${{ env.PIXI_RUN }} -e atest-${{ matrix.epoch }} ci-summary-atest
      - if: always()
        name: Publish browser test output
        uses: actions/upload-artifact@v4
        with:
          name: |-
            jplsp-${{ github.run_number }}-atest-${{ matrix.epoch }}-${{ matrix.os }}-${{ matrix.vm }}
          path: ./build/reports
