name: lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash -l {0}

env:
  CACHE_EPOCH: 1

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.platform }} py${{ matrix.python }}
    strategy:
      matrix:
        platform:
          - linux-64
        python:
          - '3.8'
        lab:
          - '2.2'
        include:
          # representative platforms
          - platform: linux-64
            os: ubuntu-16.04
          # Node 14 end-of-life: April 2023
          - python: '3.8'
            nodejs: '14'

    steps:
      - uses: actions/checkout@v2

      - name: Prep lock file
        run: |
          cp .github/conda.locks/conda.lint.${{ matrix.platform }}-${{ matrix.python }}-${{ matrix.lab }}.lock conda.lock
          cat conda.lock

      - name: Cache conda
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key: conda-lint-${{ env.CACHE_EPOCH }}-${{ matrix.platform }}-${{ matrix.python }}-${{ hashFiles('conda.lock') }}
          restore-keys: |
            conda-lint-${{ env.CACHE_EPOCH }}-${{ matrix.platform }}-${{ matrix.python }}-
            conda-lint-${{ env.CACHE_EPOCH }}-${{ matrix.platform }}-

      - name: Set up conda env
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: jupyterlab-lsp
          auto-activate-base: true
          auto-update-conda: false
          # TODO: remove once setup-miniconda supports conda lock files, save a minute
          environment-file: requirements/minimal.yml
          use-only-tar-bz2: true

      - name: Overwrite conda env from lockfile
        run: conda create --yes --name jupyterlab-lsp --file conda.lock

      - name: check integrity of package versions
        run: python scripts/integrity.py

      - name: Cache yarn
        uses: actions/cache@v2
        with:
          path: .yarn-packages
          key: yarn-${{ env.CACHE_EPOCH }}-${{ matrix.platform }}-${{ matrix.python }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-${{ env.CACHE_EPOCH }}-${{ matrix.platform }}-${{ matrix.python }}-
            yarn-${{ env.CACHE_EPOCH }}-${{ matrix.platform }}-

      - name: install npm dependencies
        run: jlpm --offline --ignore-optional || jlpm --prefer-offline --ignore-optional

      - name: lint backend
        run: python scripts/lint.py

      - name: build schema so linting can complete
        run: jlpm build:schema

      - name: lint frontend
        run: jlpm lint:check
